# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
 
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_version "2.117.1"

default_platform(:ios)
 
platform :ios do
  desc "build app"
  lane :build do
    xcbuild(
        project: "Concentration.xcodeproj",
        scheme: "Concentration",
        configuration: "Debug",
        xcargs: "-sdk iphonesimulator SYMROOT='/var/tmp/'"
    )
    copy_artifacts(
        target_path:'../eclipse-workspace/appiumtest/resources',
        artifacts:["/var/tmp/Debug-iphonesimulator/*.app"])
 end
end